name: ci-workflow
run-name: CI Pipeline
on: [push, workflow_dispatch]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v4

      - name: setup node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install deps
        run: npm ci

      - name: apply prettier
        run: npm run prettier

      - name: Perfom type check
        run: npm run typecheck

      - name: Do unit tests
        run: npm run test

      - name: Build the application
        run: npm run build

      - name: upload build artefact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'

  cd-pipline:
    needs: ci-pipeline
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-step.outputs.url_output }}
    steps:
      - name: deploy the artefact
        id: deploy-step
        uses: actions/deploy-pages@v4
